// scripts/generate-sitemap.js
// This script generates a SEO-friendly sitemap.xml for the RankersHub site.
// It scans the `app/` directory for page routes and writes the resulting XML
// to `public/sitemap.xml`. It also adds optional hreflang entries for multilingual
// sites. Adjust `BASE_URL` and `LOCALES` as needed.

const fs = require('fs');
const path = require('path');
const { create } = require('xmlbuilder2');

// ----- Configuration -------------------------------------------------------
// Base URL of the site (including protocol and domain). Update this if needed.
const BASE_URL = process.env.BASE_URL || 'https://www.rankershub.com';

// List of locale strings for hreflang. Example: ['en-US', 'fr-FR']
// Keep empty array if you do not need language/region specific URLs.
const LOCALES = process.env.LOCALES ? process.env.LOCALES.split(',') : [];

// Frequency and priority defaults – can be tuned per section later.
const DEFAULT_CHANGEFREQ = 'weekly';
const DEFAULT_PRIORITY = '0.5';

// --------------------------------------------------------------------------

/**
 * Recursively collect page routes from the `app/` directory.
 * It ignores API routes (folders containing a file named `route.ts` or `route.js`).
 * For dynamic routes (e.g., [slug]), a placeholder is kept; actual URLs should be
 * generated by a downstream process (e.g., after fetching slugs from the DB).
 */
function collectRoutes(dir, basePath = '') {
  const entries = fs.readdirSync(dir, { withFileTypes: true });
  const routes = [];
  for (const entry of entries) {
    const fullPath = path.join(dir, entry.name);
    if (entry.isDirectory()) {
      // Skip API routes
      const hasRouteFile = fs.existsSync(path.join(fullPath, 'route.ts')) ||
                           fs.existsSync(path.join(fullPath, 'route.js'));
      if (hasRouteFile) continue;
      // Build the URL segment – Next's file-system routing rules
      let segment = entry.name;
      // Dynamic segment e.g., [slug] stays as placeholder
      if (segment.startsWith('[') && segment.endsWith(']')) {
        segment = `{${segment.slice(1, -1)}}`;
      }
      const subBase = path.posix.join(basePath, segment);
      // Recurse into the folder
      routes.push(...collectRoutes(fullPath, subBase));
    } else if (entry.isFile()) {
      // Consider .tsx, .ts, .jsx, .js as potential page entry points.
      if (/[.](tsx?|jsx?)$/.test(entry.name)) {
        // If the file is named 'page.tsx' (or similar), the folder itself
        // represents a route. Otherwise, ignore file-level routes for simplicity.
        if (entry.name.startsWith('page.')) {
          routes.push(basePath || '/');
        }
      }
    }
  }
  return routes;
}

function buildUrlEntry(url) {
  const urlElem = {
    loc: url,
    changefreq: DEFAULT_CHANGEFREQ,
    priority: DEFAULT_PRIORITY,
  };
  if (LOCALES.length > 0) {
    urlElem['xhtml:link'] = LOCALES.map((locale) => ({
      '@rel': 'alternate',
      '@hreflang': locale,
      '@href': `${url}?lang=${locale}`,
    }));
  }
  return urlElem;
}

function generateSitemap() {
  const routes = collectRoutes(path.join(process.cwd(), 'app'));
  // Ensure root path '/' is included
  if (!routes.includes('/')) routes.unshift('/');

  const urlset = [];
  for (const route of routes) {
    // Skip dynamic placeholder routes – they will be ignored by Google.
    if (route.includes('{')) continue;
    const fullUrl = `${BASE_URL}${route.startsWith('/') ? '' : '/'}${route}`;
    urlset.push(buildUrlEntry(fullUrl));
  }

  const xmlObj = {
    urlset: {
      '@xmlns': 'http://www.sitemaps.org/schemas/sitemap/0.9',
      '@xmlns:xhtml': 'http://www.w3.org/1999/xhtml',
      url: urlset,
    },
  };

  const xml = create(xmlObj).end({ prettyPrint: true });
  const outPath = path.join(process.cwd(), 'public', 'sitemap.xml');
  fs.mkdirSync(path.dirname(outPath), { recursive: true });
  fs.writeFileSync(outPath, xml, 'utf8');
  console.log(`✅ Sitemap generated at ${outPath}`);
}

generateSitemap();
